name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kartik4042
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          
          plugin_notable: yes
          plugin_notable_from: organization
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
